name: DTcreature
main: me.zilo.DTcmd.DTmain
version: 0.2
commands:
   puppet:
      description: ใช่ผู้เล่นอื่นพูดแทน.
      usage: /puppet <ผู้เล่นเป้าหมาย> <ข้อความ>
      aliases: [pup]
   fakeop:
      description: ขึ้นข้อความ You are now op!.
      usage: /fakeop <ผู้เล่นเป้าหมาย>
      aliases: [fop]
permission: 
    DTcmd.*:
        description: ให้สิทธิใช้และป้องกันคำสั่งทั้งหมด
        default: op
        children:
            DTcmd.puppet: true
            DTcmd.antiPuppet: true
            DTcmd.fakeOP: true
            DTcmd.antiFakeOP: true
    DTcmd.Mod:
        description: ให้ใช้คำสั่งทั้งหมด
        default: op
        children:
            DTcmd.puppet: true
            DTcmd.fakeOP: true
    DTcmd.puppet:
        description: ให้สิทธ์ผู้เล่นใช้คำสั่ง /puppet
        default: op
    DTcmd.antiPuppet:
        description: ป้องกันจากคำสั่ง /puppet
        default: op
    DTcmd.fakeOP:
        description: ให้สิทธ์ผู้เล่นใช้คำสั่ง /fakeOP
        default: op
    DTcmd.antiFakeOP:
        description: ป้องกันจากคำสั่ง /fakeOP
        default: op
    