name: DTplugin
main: me.zilo.DTplugin.DTmain
version: 0.4
commands:
   puppet:
      description: ใช่ผู้เล่นอื่นพูดแทน.
      usage: /puppet <ผู้เล่นเป้าหมาย> <ข้อความ>
      aliases: [pup]
   fakeop:
      description: ขึ้นข้อความ You are now op!.
      usage: /fakeop <ผู้เล่นเป้าหมาย>
      aliases: [fop]
   adminchat:
      description: แอดมิน แชท.
      usage: /adminchat <ข้อความ>
      aliases: [ad]
   togglechannel:
      description: แอดมิน แชท.
      usage: /togglechannel <ข้อความ>
      aliases: [tc]
permission: 
    DTplugin.*:
        description: ให้สิทธิใช้และป้องกันคำสั่งทั้งหมด
        default: op
        children:
            DTplugin.puppet: true
            DTplugin.antiPuppet: true
            DTplugin.fakeOP: true
            DTplugin.antiFakeOP: true
            DTplugin.adminChat: true
            DTplugin.adminChannel: true;
            DTplugin.bypassDrop: true
            DTplugin.bypassPickup: true
    DTplugin.Mod:
        description: ให้ใช้คำสั่งทั้งหมด
        default: op
        children:
            DTplugin.puppet: true
            DTplugin.fakeOP: true
            DTplugin.adminChat: true
            DTplugin.adminChannel: true;
    DTplugin.puppet:
        description: ให้สิทธ์ผู้เล่นใช้คำสั่ง /puppet
        default: op
    DTplugin.antiPuppet:
        description: ป้องกันจากคำสั่ง /puppet
        default: op
    DTplugin.fakeOP:
        description: ให้สิทธ์ผู้เล่นใช้คำสั่ง /fakeOP
        default: op
    DTplugin.antiFakeOP:
        description: ป้องกันจากคำสั่ง /fakeOP
        default: op
    DTplugin.adminChat:
        description: ให้สิทธ์ผู้เล่นใช้คำสั่ง /adminchat
        default: op
    DTplugin.adminChannel:
        description: ให้สิทธ์ผู้เล่นใช้คำสั่ง /togglechannel
        default: op
    DTplugin.bypassDrop:
        description: ให้สิทธ์ผู้เล่นโยนของที่ห้ามทิ้งได้
        default: op
    DTplugin.bypassPickup:
        description: ให้สิทธ์ผู้เล่นเก็บของที่ห้ามได้
        default: op